apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2  # Set the number of pods to 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-container-1
          image: hello-world-k8s:1.0  # Replace with your image
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
        - name: hello-world-container-2
          image: hello-world-k8s:1.0  # Replace with your image
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
        - name: hello-world-container-3
          image: hello-world-k8s:1.0  # Replace with your image
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
        - name: hello-world-container-4
          image: hello-world-k8s:1.0  # Replace with your image
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
        - name: hello-world-container-5
          image: hello-world-k8s:1.0  # Replace with your image
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"

